### ISSUE TITLE
PixelInvaders on Teensy3.1 and WS2811 Led strips - is it possible?

### ISSUE THREAD

**Issue by croisez** [neophob/PixelController#75]
Hi,
I would like to know if there is a way to bring together my 128 leds ledstrip controlled by WS2811, my Teensy3.1, and PixelController program.

If yes, which ArduinoFW should I use?

Thank for your support
Louis.

**Comment by ozett** [comment]
sorry to bother in here after this time, but in the lack of a wiki i found this thread the best place to keep up with this fast running improvements for "remote-pixels".
i once tried to have pixel-matrices controlled over ethernet/artnet. i used a simple and cheap arduino-device with ethernet and an artnet-sketch. i described here.

now one can go wilder with esp8266 devices (under 2 EUR), which have wifi and there seems to be art-net libraries for ws2811/ws2812b pixels (5v). wow!!!

https://wiki.chaos-darmstadt.de/wiki/ESP8266

**Comment by ozett** [comment]
and bother again .. ;-) because of another finding:

"I was successful at driving 132 LEDs (11x12 matrix) using this firmware and the pixelcontroller (v2.1.0-RC1) software. " with ws2812 leds on ESP8266 with TPM2.net firmware 

here:
http://www.ledstyles.de/index.php/Thread/24571-esp8266-tpm2net-ws2812/?postID=351317#post351317

firmware:
https://github.com/sfranzyshen/esp8266_tpm2net

and for other leds leds :
https://github.com/sfranzyshen/esp8266_tpm2net_ws2801
https://github.com/sfranzyshen/esp8266_tpm2net_lpd6803

**Comment by mortenx** [comment]
is anyone  got it working   lpd6803 with arduino +pixelcontroller ?
